// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"go-ecommerce-backend-api/internal/controller"
	"go-ecommerce-backend-api/internal/repo/impl"
	impl2 "go-ecommerce-backend-api/internal/service/impl"
)

// Injectors from product.wire.go:

func InitProductRouterHandler() (*controller.ProductController, error) {
	productRepo := impl.NewProductRepo()
	iProductService := impl2.NewProductService(productRepo)
	productController := controller.NewProductController(iProductService)
	return productController, nil
}
