// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"go-ecommerce-backend-api/internal/controller"
	"go-ecommerce-backend-api/internal/grpc"
	"go-ecommerce-backend-api/internal/repo/impl"
	"go-ecommerce-backend-api/internal/service"
	impl2 "go-ecommerce-backend-api/internal/service/impl"
)

// Injectors from inventory.wire.go:

func InitInventoryRouterHandler() (*controller.InventoryController, error) {
	iInventoryRepo := impl.NewInventoryRepo()
	iInventoryService := impl2.NewInventoryService(iInventoryRepo)
	inventoryController := controller.NewInventoryController(iInventoryService)
	return inventoryController, nil
}

// Injectors from inventory_pb.wire.go:

// InitInventoryGrpcServer initializes the gRPC server
func InitInventoryGrpcServer() (*grpc.InventoryServer, error) {
	iInventoryRepo := impl.NewInventoryRepo()
	iInventoryService := impl2.NewInventoryService(iInventoryRepo)
	inventoryServer := provideInventoryServer(iInventoryService)
	return inventoryServer, nil
}

// inventory_pb.wire.go:

// provideInventoryServer creates a new inventory gRPC server
func provideInventoryServer(inventoryService service.IInventoryService) *grpc.InventoryServer {
	return grpc.NewInventoryServer(inventoryService)
}
