apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  labels:
    app.kubernetes.io/name: inventory-deployment
    app.kubernetes.io/instance: inventory
    app.kubernetes.io/component: inventory
    app.kubernetes.io/part-of: go-microservice
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: inventory-service
        app.kubernetes.io/instance: inventory
        app.kubernetes.io/component: inventory
        app.kubernetes.io/part-of: go-microservice
    spec:
      containers:
        - name: inventory
          image: inventory-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9090
              name: grpc
          env:
            - name: SERVICE_NAME
              value: "inventory-service"
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USERNAME
              value: "root"
            - name: MYSQL_PASSWORD
              value: "password"
            - name: MYSQL_DBNAME
              value: "inventory"
            - name: REDIS_HOST
              value: "root"
            - name: REDIS_PORT
              value: "password"
            - name: REDIS_PASSWORD
              value: "inventory"
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi