# 2025
version: '3.2'

networks:
  pre-go-local-networks:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: shopdevgo
      MYSQL_PASSWORD: root1234
    ports:
      - "33306:3306"
    volumes:
      - ./data/mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--skip-character-set-client-handshake'  # Buộc tất cả kết nối sử dụng utf8mb4
    ]
    networks:
      - pre-go-local-networks

  #support bloom filters
  redis:
    image: redis/redis-stack:latest
    container_name: redis_container_bloom
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis_data:/data
    networks:
      - pre-go-local-networks    

#  prometheus:
#    image: prom/prometheus:latest
#    container_name: pre-event-prometheus
#    restart: unless-stopped
#    volumes:
#      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#      - ./data/prometheus_data:/prometheus
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '--storage.tsdb.path=/prometheus'
#      - '--web.console.libraries=/etc/prometheus/console_libraries'
#      - '--web.console.templates=/etc/prometheus/consoles'
#      - '--web.enable-lifecycle'
#    extra_hosts:
#      - host.docker.internal:host-gateway
#    ports:
#      - "9092:9090"
#    networks:
#      - pre-go-local-networks
#
#  grafana:
#    image: grafana/grafana
#    container_name: pre-event-grafana
#    hostname: grafana
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#      - GF_USERS_ALLOW_SING_UP=false
#      - GF_SERVER_DOMAIN=localhost
#      #enable logger
#      - GF_LOG_MODE=console file
#      - GF_LOG_FILTERS=alerting.notifier.slack:debug alermanager:debug ngalert:debug
#
#    volumes:
#      - ./grafana-storage:/var/lib/grafana
#    ports:
#      - "3002:3000"
#    networks:
#      - pre-go-local-networks

#  shopdevgo:
#    container_name: shopdevgo
##    build:
##      context: .
##      dockerfile: ../Dockerfile
#    image: shopdevgo
#    restart: always
#    depends_on:
#      - mysql
#      - redis
#    ports:
#      - "8080:8080"
#    networks:
#      - pre-go-local-networks