global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "shopdev-go-api"
    scrape_interval: 5s
    static_configs:
      - targets: ["shopdevgo:8080"]

  - job_name: "shopdev-go-prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["pre-event-prometheus:9092"]

  # - job_name: "shopdev-go-mysql-exporter"
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: [ "host.docker.internal:9104" ]
  #   metrics_path: "/metrics"         
